### ISSUE TITLE
[boost_generator] fails if use_always_short_paths = True

### ISSUE THREAD

**Issue by db4** [bincrafters/community#1060]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost_generator/1.69.0**
  * Operating System+version: **Windows 10**

For some reason I need
```
[general]
default_profile = default
```
in `conan.conf`. Having that any build that uses boost_generator fails:
```
boost_python/1.69.0@bincrafters/stable: Building your package in D:/.conan\5fe3e9\1
Traceback (most recent call last):
  File "D:\.conan\data\boost_generator\1.69.0\bincrafters\stable\export\conanfile.py", line 44, in content
    jamroot_content = self.get_template_content() \
  File "D:\.conan\data\boost_generator\1.69.0\bincrafters\stable\export\conanfile.py", line 84, in get_template_content
    template_content = load(template_file_path)
  File "c:\python37\lib\site-packages\conans\util\files.py", line 214, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/.conan\\90453a\\1\\..\\..\\export\\jamroot.template'
boost_python/1.69.0@bincrafters/stable: ERROR: Traceback (most recent call last):
  File "c:\python37\lib\site-packages\conans\client\generators\__init__.py", line 104, in write_generators
    content = generator.content
  File "D:\.conan\data\boost_generator\1.69.0\bincrafters\stable\export\conanfile.py", line 80, in content
    raise e
  File "D:\.conan\data\boost_generator\1.69.0\bincrafters\stable\export\conanfile.py", line 44, in content
    jamroot_content = self.get_template_content() \
  File "D:\.conan\data\boost_generator\1.69.0\bincrafters\stable\export\conanfile.py", line 84, in get_template_content
    template_content = load(template_file_path)
  File "c:\python37\lib\site-packages\conans\util\files.py", line 214, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/.conan\\90453a\\1\\..\\..\\export\\jamroot.template'
```

**Comment by bjayanth** [comment]
Looks like boost_generator/1.66.0 had this problem too.
