### ISSUE TITLE
[QT] Build fails due to dependency conflicts from different user(s)/channel(s)

### ISSUE THREAD

**Issue by kasunch** [bincrafters/community#1115]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.14.0@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 7**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.21.1**
  * Python version: **Python 3.7.5**

### Conan profile
```
+----------------------+
| Profile              |
|----------------------|
| include(default)     |
|                      |
| [settings]           |
| arch=x86_64          |
| build_type=Release   |
| compiler=gcc         |
| compiler.version=7   |
| [options]            |
| qt:qtwebsockets=True |
| qt:qtserialport=True |
| qt:qtmultimedia=True |
| qt:shared=True       |
| [env]                |
|                      |
| [build_requires]     |
+----------------------+

```

### Problem

I am using Azure Pipelines to compile QT with additional modules such as qserialport. 
I specify these modules via environment variables as follows in the YML file (I am using my own file).

```
matrix:
  GCC 7 x86_64:
    CONAN_GCC_VERSIONS: 7
    CONAN_DOCKER_IMAGE: conanio/gcc7
    CONAN_BUILD_TYPES: Release
    CONAN_ARCHS: "x86_64"
    CONAN_OPTIONS: "qt:qtwebsockets=True,qt:qtserialport=True,qt:qtmultimedia=True"
    CONAN_VERSION: "5.14.0"
```
Looks like recent dependency migration to conan center causes the build to fail. 
Any idea to fix for this problem?

Thanks a lot.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```

 >> Remote for URL 'https://conan.bintray.com' already exist, keeping the current remote and its name
CC and CXX: /usr/bin/gcc, /usr/bin/g++ 
Found gcc 7
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/conan/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Profile created with detected settings: /home/conan/.conan/profiles/default

****************************************************************************************************
+----------------------+
| Profile              |
|----------------------|
| include(default)     |
|                      |
| [settings]           |
| arch=x86_64          |
| build_type=Release   |
| compiler=gcc         |
| compiler.version=7   |
| [options]            |
| qt:qtwebsockets=True |
| qt:qtserialport=True |
| qt:qtmultimedia=True |
| qt:shared=True       |
| [env]                |
|                      |
| [build_requires]     |
+----------------------+

[conan_create]

 >> Calling 'conan create'
+-----------------+------------------------------------------------------+
| Configuration   | value                                                |
|-----------------+------------------------------------------------------|
| name            | qt                                                   |
| version         | 5.14.0                                               |
| user            | bincreators                                          |
| channel         | testing                                              |
| build_modes     | ['outdated']                                         |
| profile_name    | /tmp/tmp1b02kuqaconan_package_tools_profiles/profile |
+-----------------+------------------------------------------------------+
Exporting package recipe
qt/5.14.0@bincreators/testing exports: File 'conandata.yml' found. Exporting it...
qt/5.14.0@bincreators/testing exports: Copied 1 '.yml' file: conandata.yml
qt/5.14.0@bincreators/testing exports: Copied 1 '.conf' file: qtmodules.conf
qt/5.14.0@bincreators/testing exports: Copied 5 '.diff' files
qt/5.14.0@bincreators/testing: A new conanfile.py version was exported
qt/5.14.0@bincreators/testing: Folder: /home/conan/.conan/data/qt/5.14.0/bincreators/testing/export
qt/5.14.0@bincreators/testing: Exported revision: e1b80dc6d087e7125ffd8b664515cd29
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
qt:qtmultimedia=True
qt:qtserialport=True
qt:qtwebsockets=True
qt:shared=True
[build_requires]
[env]

zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'upload_repo'...
zlib/1.2.11: Trying with 'conan-center'...
Downloading conanmanifest.txt


Downloading conanfile.py


Downloading conan_export.tgz




zlib/1.2.11: Downloaded recipe revision 0
openssl/1.1.1d: Not found in local cache, looking in remotes...
openssl/1.1.1d: Trying with 'upload_repo'...
openssl/1.1.1d: Trying with 'conan-center'...
Downloading conanmanifest.txt


Downloading conanfile.py


Downloading conan_export.tgz




openssl/1.1.1d: Downloaded recipe revision 0
pcre2/10.33: Not found in local cache, looking in remotes...
pcre2/10.33: Trying with 'upload_repo'...
pcre2/10.33: Trying with 'conan-center'...
Downloading conanmanifest.txt


Downloading conanfile.py


Downloading conan_export.tgz




pcre2/10.33: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'upload_repo'...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt


Downloading conanfile.py


Downloading conan_export.tgz




bzip2/1.0.8: Downloaded recipe revision 0
glib/2.58.3@bincrafters/stable: Not found in local cache, looking in remotes...
glib/2.58.3@bincrafters/stable: Trying with 'upload_repo'...
Downloading conanmanifest.txt


Downloading conanfile.py


Downloading conan_export.tgz




glib/2.58.3@bincrafters/stable: Downloaded recipe revision 0
libffi/3.2.1@bincrafters/stable: Not found in local cache, looking in remotes...
libffi/3.2.1@bincrafters/stable: Trying with 'upload_repo'...
libffi/3.2.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt


Downloading conanfile.py


libffi/3.2.1@bincrafters/stable: Downloaded recipe revision 0
pcre/8.41@bincrafters/stable: Not found in local cache, looking in remotes...
pcre/8.41@bincrafters/stable: Trying with 'upload_repo'...
pcre/8.41@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt


Downloading conanfile.py


Downloading conan_export.tgz




pcre/8.41@bincrafters/stable: Downloaded recipe revision 0
WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json
WARN: glib/2.58.3@bincrafters/stable: requirement zlib/1.2.11@conan/stable overridden by qt/5.14.0@bincreators/testing to zlib/1.2.11 
WARN: pcre/8.41@bincrafters/stable: requirement zlib/1.2.11@conan/stable overridden by glib/2.58.3@bincrafters/stable to zlib/1.2.11 
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.5/bin/run_create_in_docker", line 11, in <module>
    load_entry_point('conan-package-tools==0.30.4', 'console_scripts', 'run_create_in_docker')()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/cpt/run_in_docker.py", line 53, in run
    runner.run()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/cpt/runner.py", line 122, in run
    update=self._update_dependencies)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/conan_api.py", line 364, in create
    test_build_folder, test_folder, conanfile_path, recorder=recorder)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cmd/create.py", line 43, in create
    recorder=recorder)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cmd/test.py", line 38, in install_build_and_test
    recorder=recorder)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/manager.py", line 47, in deps_install
    False, update, remotes, recorder)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 110, in load_graph
    recorder, apply_build_requires=apply_build_requires)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 236, in _resolve_graph
    graph_lock=graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 338, in _load_graph
    graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 40, in load_graph
    profile_host, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 128, in _load_deps
    remotes, profile_host, new_reqs, new_options, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 176, in _handle_require
    update, remotes, profile_host, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 128, in _load_deps
    remotes, profile_host, new_reqs, new_options, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 176, in _handle_require
    update, remotes, profile_host, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 128, in _load_deps
    remotes, profile_host, new_reqs, new_options, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 176, in _handle_require
    update, remotes, profile_host, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 128, in _load_deps
    remotes, profile_host, new_reqs, new_options, graph_lock)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 187, in _handle_require
    self._conflicting_references(previous.ref, require.ref, node.ref)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 219, in _conflicting_references
    % (consumer_ref, new_ref, previous_ref))
conans.errors.ConanException: Conflict in pcre/8.41@bincrafters/stable
    Requirement bzip2/1.0.8@conan/stable conflicts with already defined bzip2/1.0.8
    To change it, override it in your base requirements
Traceback (most recent call last):
  File "build.py", line 8, in <module>
    builder.run()
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/cpt/packager.py", line 517, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/cpt/packager.py", line 639, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/cpt/runner.py", line 299, in run
    raise Exception("Error building: %s" % command)
```

</details>

**Comment by ericLemanissier** [comment]
can you retry with `-u` argument, to update the dependencies ?

**Comment by kasunch** [comment]
Thanks for the prompt reply. As I am using Azure Pipelines, I set the environmental variable CPT_UPDATE_DEPENDENCIES=1 and also CONAN_UPDATE_DEPENDENCIES=1 (I found this while looking at the source of CPT and not sure if I need to use this). I can see that "update_dependencies" is set to "True" in the log of CPT as follows. 

```
[local_vars]
+---------------------------+---------------------+
| Configuration             | value               |
|---------------------------+---------------------|
| cwd                       | /home/vsts/work/1/s |
| username                  | bincreators         |
| skip_check_credentials    | False               |
| upload_only_when_stable   | True                |
| upload_only_when_tag      | False               |
| upload_only_recipe        | False               |
| stable_branch_pattern     | stable/*            |
| stable_channel            | stable              |
| partial_reference         | qt/5.14.0           |
| channel                   | testing             |
| conanfile                 | conanfile.py        |
| use_docker                | True                |
| docker_conan_home         | /home/conan         |
| build_policy              | outdated            |
| sudo_docker_command       | sudo -E             |
| sudo_pip_command          |                     |
| pip_command               | pip                 |
| docker_shell              | /bin/sh -c          |
| docker_platform_param     |                     |
| lcow_user_workaround      |                     |
| exclude_vcvars_precommand | False               |
| upload_dependencies       | all                 |
| update_dependencies       | True                |
| docker_32_images          | False               |
| force_selinux             | False               |
| conan_pip_package         | conan==1.21.1       |
| vs10_x86_64_enabled       | False               |
| builds_in_current_page    | []                  |
| skip_recipe_export        | False               |
+---------------------------+---------------------+
```

However the problem still exist.
Which variables do you specify when you use your CI?

**Comment by ericLemanissier** [comment]
We can see in the log that it is downloading all recipes, so they should be up to date.
The following line makes no sense to me: `WARN: glib/2.58.3@bincrafters/stable: requirement zlib/1.2.11@conan/stable overridden by qt/5.14.0@bincreators/testing to zlib/1.2.11`
glib/2.58.3 requires zlib/1.2.11, not the @conan/stable outdated version: https://github.com/bincrafters/conan-glib/blob/stable/2.58.3/conanfile.py#L34
Is this log recent ? do you have the bincrafters remote (https://api.bintray.com/conan/bincrafters/public-conan) set up properly ?

**Comment by kasunch** [comment]
I just did a build just to make sure. The same result.
Please find the attached log file.
[4_CmdLine.txt](https://github.com/bincrafters/community/files/4135047/4_CmdLine.txt)

**Comment by ericLemanissier** [comment]
There is an outdated version of glib in your bintray. Please remove it or update it.

**Comment by kasunch** [comment]
Yep. That is it. Deleted all obsolete packages. Now it works.
Thanks a lot for your prompt support.
