### ISSUE TITLE
Additional options for cygwin_installer

### ISSUE THREAD

**Issue by db4** [bincrafters/community#233]
I would love to see the following options added to cygwin_installer (maybe named differently):

- noacl: [False, True], defaullt=False
  If True, adds `noacl` mount option to `/etc/fstab`
```
none /cygdrive cygdrive noacl,binary,posix=0,user 0 0
```
This helps to avoid many subtle problems like https://stackoverflow.com/questions/32078794/file-permissions-changed-in-build-process-compilation-aborts-because-access-den/32112801

- cygwin: ANY
  sets CYGWIN environment variable. E.g. `-o cygwin_installer:cygwin=winsymlinks:native` will `set CYGWIN=winsymlinks:native` and instruct cygwin to create normal Windows symlinks that can be handled by any Win32 application (more details: https://cygwin.com/cygwin-ug-net/using.html#pathnames-symlink)

- db_home: ANY
  If set, will add 
```
db_home: <value>
```
to `/etc/nsswitch.conf` More detail on the setting: https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-mapping-nsswitch E.g. `-o cygwin_installer:db_home=windows` sets cygwin home directory to the same directory which is used as Windows home directory.

**Comment by SSE4** [comment]
thanks for your suggestions! I'll be adding options you have mentioned, I'll keep you informed.

**Comment by SSE4** [comment]
@db4 I've added requested options, please give a try

**Comment by db4** [comment]
@SSE4 thanks a lot!

It almost works, but I have a problem with `cygwin` option. The following `conanfile.txt`
```
[requires]
cygwin_installer/2.9.0@bincrafters/testing
[options]
cygwin_installer:cygwin=winsymlinks::native
[generators]
virtualenv
```
causes python exception inside conan (CONAN_VERBOSE_TRACEBACK=1):
```
...
cygwin_installer/2.9.0@bincrafters/testing: Creating CYGWIN env var : winsymlinks:native
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\conans\model\ref.py", line 70, in loads
    name, version, user, channel = tokens
ValueError: not enough values to unpack (expected 4, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\conans\client\command.py", line 293, in install
    reference = ConanFileReference.loads(args.path)
  File "c:\python36\lib\site-packages\conans\model\ref.py", line 73, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference .
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\conans\client\command.py", line 1187, in run
    method(args[0][1:])
  File "c:\python36\lib\site-packages\conans\client\command.py", line 304, in install
    install_folder=args.install_folder)
  File "c:\python36\lib\site-packages\conans\client\conan_api.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "c:\python36\lib\site-packages\conans\client\conan_api.py", line 444, in install
    no_imports=no_imports)
  File "c:\python36\lib\site-packages\conans\client\manager.py", line 404, in install
    write_generators(conanfile, install_folder, output)
  File "c:\python36\lib\site-packages\conans\client\generators\__init__.py", line 81, in write_generators
    generator = generator_class(conanfile)
  File "c:\python36\lib\site-packages\conans\client\generators\virtualenv.py", line 12, in __init__
    self.env = conanfile.env
  File "c:\python36\lib\site-packages\conans\model\conan_file.py", line 179, in env
    tmp_env_values.update(self.deps_env_info)
  File "c:\python36\lib\site-packages\conans\model\env_info.py", line 146, in update
    self.add(name, value)
  File "c:\python36\lib\site-packages\conans\model\env_info.py", line 108, in add
    self._data[package][name] = value.replace("\\", "/")
AttributeError: 'PackageOption' object has no attribute 'replace'

ERROR: 'PackageOption' object has no attribute 'replace'
```

**Comment by SSE4** [comment]
@db4 thanks for the reporting. will fix issue with additional_packages, and try to debug conan error as well.

**Comment by db4** [comment]
Great, thanks!

**Comment by db4** [comment]
You can close this issue as well

**Comment by SSE4** [comment]
@db4 thanks again!
