### ISSUE TITLE
libcurl: error trying to import .so files

### ISSUE THREAD

**Issue by piponazo** [bincrafters/community#436]
### Description of Problem, Request, or Question
When I try to import the .so files from the libcurl package to a local folder, I get the following error when calling `conan install ..`:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/command.py", line 1287, in run
    method(args[0][1:])
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/command.py", line 336, in install
    install_folder=args.install_folder)
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/conan_api.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/conan_api.py", line 471, in install
    no_imports=no_imports)
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/manager.py", line 169, in install
    run_imports(conanfile, install_folder, output)
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/importer.py", line 86, in run_imports
    _report_save_manifest(copied_files, import_output, dest_folder, IMPORTS_MANIFESTS)
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/client/importer.py", line 61, in _report_save_manifest
    file_dict[f] = md5sum(abs_path)
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/util/files.py", line 82, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/media/linuxDev/envs/conan/lib/python3.6/site-packages/conans/util/files.py", line 95, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/media/linuxDev/programming/exiv2/build/conanLibs/libcurl.so'

ERROR: [Errno 2] No such file or directory: '/media/linuxDev/programming/exiv2/build/conanLibs/libcurl.so'
```
This is what I have in the `conanfile.py` of my project:
```
    def imports(self):
        self.copy('*.dll', dst='conanLibs', src='bin')
        self.copy('*.dylib', dst='conanLibs', src='lib')
        self.copy('*.so', dst='conanLibs', src='lib')
```
It seems to be a problem copying the symlinks and I am not sure if this is a problem with this package or with conan. Note that I can import .so files from other packages without problems.

### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.60.0:stable**
* Operating System: **Linux Ubuntu 18.04**
* Compiler+version: **gcc-7.3**

### Steps to reproduce (Include if Applicable)
Try to run `conan install` with this conanfile.txt:
```
[requires]
libcurl/7.60.0@bincrafters/stable

[options]
libcurl:shared=True

[generators]
cmake

[imports]
lib, *.so -> libs
```

**Comment by piponazo** [comment]
Thanks, it works like that :smile: .
