### ISSUE TITLE
[boost_serialization] 1.67.0 recipe is missing conanmanifest.txt

### ISSUE THREAD

**Issue by datalogics-kam** [bincrafters/community#643]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost_serialization/1.67.0**
  * Operating System+version: **macOS Mojave 10.14.3**
  * Compiler+version: *apple-clang 9.1 (Xcode 9.4.1)*
  * Docker image: n/a
  * Conan version: **conan 1.8.4**
  * Python version: **Python 3.6.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile apple-clang-9.1-macos-10.7:

[settings]
os=Macos
os.version=10.7
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=9.1
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
MACOSX_DEPLOYMENT_TARGET=10.7
```

### Steps to reproduce (Include if Applicable)

```
conan install boost_serialization/1.67.0@bincrafters/stable -pr apple-clang-9.1-macos-10.7 -s arch=x86 --build missing
```

### Logs (Include/Attach if Applicable)

```
boost_serialization/1.67.0@bincrafters/stable: Build folder /Users/kam/.conan/data/boost_serialization/1.67.0/bincrafters/stable/build/ade8263b79c712c55831446da30afaed317b3aef
Traceback (most recent call last):
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/command.py", line 1380, in run
    method(args[0][1:])
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/command.py", line 395, in install
    install_folder=args.install_folder)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/conan_api.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/conan_api.py", line 462, in install_reference
    generators=generators)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/manager.py", line 147, in install
    installer.install(deps_graph, keep_build)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/installer.py", line 273, in install
    self._build(nodes_by_level, deps_graph, keep_build, root_node)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/installer.py", line 299, in _build
    self._handle_node_cache(node, package_ref, keep_build, processed_package_refs)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/installer.py", line 314, in _handle_node_cache
    self._build_package(node, package_ref, output, keep_build)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/installer.py", line 386, in _build_package
    builder.package()
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/installer.py", line 123, in package
    manifest = self._client_cache.load_manifest(self._conan_ref)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/client/client_cache.py", line 236, in load_manifest
    return FileTreeManifest.load(export_folder)
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/model/manifest.py", line 77, in load
    text = load(os.path.join(folder, CONAN_MANIFEST))
  File "/Users/kam/.virtualenvs/ocrbox-b0kvYMu2/lib/python3.6/site-packages/conans/util/files.py", line 189, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kam/.conan/data/boost_serialization/1.67.0/bincrafters/stable/export/conanmanifest.txt'
```

**Comment by solvingj** [comment]
I out of curiousity, why x86?

@uilianries is conanmanifest.txt generated on the client side?  I think it must since this is a case where it was a build missing.

@datalogics-kam , try conan remove on it and rebuild.

**Comment by uilianries** [comment]
@solvingj this issue is related to:

https://github.com/conan-io/conan/issues/3817
https://github.com/conan-io/conan/issues/4388

We dont have many options, send a report to Bintray team, but we will to remove that package from bintray and upload it again.

**Comment by solvingj** [comment]
I guess i still don't understand how the `conanmanifest.txt` can be broken for `boost_regex`, but only for this variant which we don't build with CI.  But, the same package worked fine for all the packages which depended on it (and for which we did build with CI).

**Comment by datalogics-kam** [comment]
@solvingj x86 is a requirement for one of our products; customers still use some of our software in 32-bit. If it's not in Bintray, I've got tools to upload the packages to our local Artifactory.

Ok, I'm giving it another try. I totally removed all my Conan packages from the local cache (`conan remove "*" --force`).

Still breaks for me. I think it's the _recipe_ that doesn't have a `conanmanifest.txt`.

I mean, if I look [here](https://bintray.com/bincrafters/public-conan/boost_serialization%3Abincrafters/1.67.0%3Astable#files/bincrafters%2Fboost_serialization%2F1.67.0%2Fstable%2Fexport), shouldn't there be a `conanmanifest.txt` there?

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/89971/52763289-d12bd000-2fe0-11e9-92aa-7c6f922fead1.png">

Ok, let me try another tack. Let's start from the git repo and export the recipe to my local cache.

```
$ git clone git@github.com:bincrafters/conan-boost_serialization.git
$ cd conan-boost_serialization
$ git checkout stable/1.67.0
$ conan export . bincrafters/stable
$ ls /Users/kam/.conan/data/boost_serialization/1.67.0/bincrafters/stable/export
LICENSE.md        conanfile.py      conanmanifest.txt
$ conan install boost_serialization/1.67.0@bincrafters/stable -pr apple-clang-9.1-macos-10.7 -s arch=x86 --build missing
```

...and that works.

```
$ conan remove boost_serialization/1.67.0@bincrafters/stable
$ conan install boost_serialization/1.67.0@bincrafters/stable -pr apple-clang-9.1-macos-10.7 -s arch=x86 --build missing
...fails...
$ ls /Users/kam/.conan/data/boost_serialization/1.67.0/bincrafters/stable/export
LICENSE.md   conanfile.py
```

So I think that somehow the `conanmanifest.txt` got lost out of the recipe on Bintray.

Does that help define the problem more clearly?

**Comment by solvingj** [comment]
If it’s that, we can probably copy that one file from testing branch to stable. Will try in AM.

**Comment by solvingj** [comment]
On second thought, try using testing branch in whatever boost libs you are directly requiring.  It’s equivalent, and will probably confirm it’s a package corruption issue.

**Comment by uilianries** [comment]
> I guess i still don't understand how the `conanmanifest.txt` can be broken for `boost_regex`, but only for this variant which we don't build with CI. But, the same package worked fine for all the packages which depended on it (and for which we did build with CI).

We found a similar problem few weeks ago. Only the manifest file was corrupted for a specific job on OSX. We needed to remove that file and upload the package again.

**Comment by datalogics-kam** [comment]
> On second thought, try using testing branch in whatever boost libs you are directly requiring.

Changing the `conan install` example above to `bincrafters/testing` did indeed work.

**Comment by solvingj** [comment]
Great, we'll fix ASAP.

**Comment by SSE4** [comment]
@danimtb do you think if it might be bintray issue?

**Comment by danimtb** [comment]
Looks like same issue in Bintray. What @uilianries pointed out should be the way to solve it. I have not much to say... sorry guys

**Comment by Croydon** [comment]
Can this be closed?

**Comment by datalogics-kam** [comment]
> Can this be closed?

I'm redoing our Artifactory setup, updating to Conan 1.17.2 (on the way to 1.18), and using Artifactory 6.11.3 with virtual repositories and a remote for bincrafters, and I'm still having problems with this.

Conan says:

```
conans.errors.NotFoundException: Unable to find 'boost_serialization/1.67.0@bincrafters/stable' in remotes
```

Artifactory `system.log` says:

```
2019-08-13 13:38:08,320 [http-nio-8081-exec-2] [INFO ] (o.a.r.HttpRepo      :432) - conan-center-remote downloading https://conan.bintray.com/v2/conans/boost_serialization/1.67.0/bincrafters/stable/revisions 100 bytes 
2019-08-13 13:38:08,323 [http-nio-8081-exec-2] [INFO ] (o.a.r.HttpRepo      :445) - conan-center-remote downloaded  https://conan.bintray.com/v2/conans/boost_serialization/1.67.0/bincrafters/stable/revisions 100 bytes at 35.29 KB/sec
2019-08-13 13:38:08,372 [http-nio-8081-exec-2] [ERROR] (o.a.a.c.r.ConanV2RemoteRepoHandler:261) - Unable to fetch latest revision from 'https://conan.bintray.com/v2/conans/boost_serialization/1.67.0/bincrafters/stable/latest': HTTP/1.1 404 Not Found
2019-08-13 13:38:08,665 [http-nio-8081-exec-10] [INFO ] (o.a.r.HttpRepo      :432) - bincrafters-remote downloading https://api.bintray.com/conan/bincrafters/public-conan/v2/conans/boost_serialization/1.67.0/bincrafters/stable/revisions 100 bytes 
2019-08-13 13:38:08,670 [http-nio-8081-exec-10] [INFO ] (o.a.r.HttpRepo      :445) - bincrafters-remote downloaded  https://api.bintray.com/conan/bincrafters/public-conan/v2/conans/boost_serialization/1.67.0/bincrafters/stable/revisions 100 bytes at 22.10 KB/sec
2019-08-13 13:38:08,731 [http-nio-8081-exec-10] [ERROR] (o.a.a.c.r.ConanV2RemoteRepoHandler:261) - Unable to fetch latest revision from 'https://api.bintray.com/conan/bincrafters/public-conan/v2/conans/boost_serialization/1.67.0/bincrafters/stable/latest': HTTP/1.1 404 Not Found
```

**Comment by Croydon** [comment]
![manifest](https://user-images.githubusercontent.com/1593194/107075140-ffb49e00-67e9-11eb-9221-c6660c84dcf1.PNG)

We will soon announce changes to our infrastructure. As a nice side-effect, this bug seems to be solved. 

`boost_serialization/1.67.0@bincrafters/stable` will have a `conanmanifest.txt` file. The lack of this file seems to be the problem in this issue.
