### ISSUE TITLE
wxWidgets 3.1.2 Conan fails to download GCC binary packages

### ISSUE THREAD

**Issue by ph1ll** [bincrafters/community#751]
Hi,

I am having an issue with `wxwidgets/3.1.2@bincrafters/stable`, in that the binary packages are failing for GCC - both Debug and Release for GCC-7 and GCC-8. I'm new to Conan, so have struggled to debug the error further, but it appears that the package downloads and then possibly fails to unpack. Note that `wxwidgets/3.1.1@bincrafters/stable` works without issue.

I have created a GitHub repo to reproduce the issue, in the same manner as my own project, together with builds on Travis to demonstrate the problem (links below).

Thanks in advance.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wxWidgets/3.1.2**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-8**
  * Conan version: **conan 1.14.4**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
https://github.com/ph1ll/wx3.1.2gcc  
https://travis-ci.org/ph1ll/wx3.1.2gcc/builds/525549333

### Logs (Include/Attach if Applicable)
```
wxwidgets/3.1.2@bincrafters/stable: Retrieving package abaf83d59cf364231fd13ed1a032a2a5dcd1e643 from remote 'bincrafters' 
Downloading conanmanifest.txt

Downloading conaninfo.txt

Downloading conan_package.tgz

....
wxwidgets/3.1.2@bincrafters/stable: ERROR: Exception while getting package: abaf83d59cf364231fd13ed1a032a2a5dcd1e643
wxwidgets/3.1.2@bincrafters/stable: ERROR: Exception: <class 'FileNotFoundError'> [Errno 2] No such file or directory
wxwidgets/3.1.2@bincrafters/stable: WARN: Trying to remove package folder: /home/travis/.conan/data/wxwidgets/3.1.2/bincrafters/stable/package/abaf83d59cf364231fd13ed1a032a2a5dcd1e643
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/model/ref.py", line 111, in loads
    _, name, version, user, channel, revision, _ = ConanFileReference.sep_pattern.split(text)
ValueError: not enough values to unpack (expected 7, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 377, in install
    ref = ConanFileReference.loads(args.path_or_reference)
  File "/usr/local/lib/python3.5/dist-packages/conans/model/ref.py", line 114, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference .
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1579, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 390, in install
    install_folder=args.install_folder)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 580, in install
    no_imports=no_imports)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/manager.py", line 80, in install
    installer.install(deps_graph, keep_build)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/installer.py", line 302, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/installer.py", line 324, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/installer.py", line 395, in _handle_node_cache
    self._recorder)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/remote_manager.py", line 148, in get_package
    touch_folder(dest_folder)
  File "/usr/local/lib/python3.5/dist-packages/conans/util/files.py", line 76, in touch_folder
    os.utime(os.path.join(dirname, fname), None)
FileNotFoundError: [Errno 2] No such file or directory

ERROR: [Errno 2] No such file or directory
CMake Error at cmake/conan.cmake:383 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:463 (conan_cmake_install)
  CMakeLists.txt:46 (conan_cmake_run)
```

**Comment by nkshigeru** [comment]
I am not Linux user, but there is same issue on mac.
I found that `wxrc` and `wx-config` symlinks in binary packages are absolute so extracting package will fail when downloading.

See bincrafters/conan-wxwidgets#9

**Comment by SSE4** [comment]
merged

**Comment by ph1ll** [comment]
Many thanks for the help and quick resolution, the builds are now all passing (https://travis-ci.org/ph1ll/wx3.1.2gcc/builds/525549333)
